---
- name: Change motd with facts and well-wishes
  hosts: localhost
  become: yes
  tasks:
    - name: Update /etc/motd with system info
      ansible.builtin.copy:
        content: |
          Hostname: {{ ansible_hostname }}
          IP Address: {{ ansible_default_ipv4.address }}
          Have a nice day, sysadmin!
        dest: /etc/motd
        owner: root
        group: root
        mode: '0644'
